# Dim the hallway lights so they're not blinding at night
- alias: Dim Hallway Lights
  description: Dim the Hallway Lights for night use
  trigger:
  - at: '21:35:00'
    platform: time
  condition: []
  action:
    service: script.dim_ikea_light
    data_template:
      # Variables that are passed on to the script:
      entity: group.hallway_lights
      color_temp: 450
      brightness_pct: 1

# Reset the hallway lights for day usage
- alias: Reset Hallway Lights
  description: Reset the Hallway Lights for day use
  trigger:
  - at: '07:35:00'
    platform: time
  condition: []
  action:
    service: script.dim_ikea_light
    data_template:
      # Variables that are passed on to the script:
      entity: group.hallway_lights
      color_temp: 250
      brightness_pct: 100
