homeassistant_latitude: 000.0000000
homeassistant_longitude: 000.0000000
homeassistant_elevation: 00
http_base_url: ha.local
http_password: password
http_port: 80
external_ip: 8.8.8.8
server_port: 8123
MQTT_username: MQTT_username
MQTT_password: password
qnap_user: qnap_username
qnap_pass: password
plex_token: plex_token
blink_username: blink_user
blink_password: blink_password