# https://www.wouterbulten.nl/blog/tech/ikea-tradfri-temp-and-brightness-with-home-assistant/

sunrise_ikea_light:
  sequence:
    # Check whether the light is off (optional)
    #- condition: template
    #  value_template: "{{ is_state(entity, 'off') }}"
    #- delay: '00:00:01'
    
    # Set the initial brightness of the light
    - service: light.turn_on
      data_template:
        entity_id: "{{ entity }}"
        brightness: 1
    - delay: '00:00:01'
    
    # Set the color temperature (Focus: 250, Everyday: 370, Relax: 450)
    - service: light.turn_on
      data_template:
        entity_id: "{{ entity }}"
        color_temp: "{{ color_temp }}"
        transition: 5
    - delay: '00:00:01'

    # Set the brightness transition time of the Sunrise
    - service: light.turn_on
      data_template:
        entity_id: "{{ entity }}"
        brightness: 255
        transition: "{{ transition_time }}"